package com.zhu.kaoqin.entity;

// Generated 2013-4-9 11:30:31 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Kaoqin generated by hbm2java
 */
@Entity
@Table(name = "kaoqin", catalog = "kaoqin")
public class KaoqinEntity implements Serializable {

	/**
	 * 
	 * @作者：朱伟亮
	 * @创建时间：2013-4-9 下午4:38:35
	 */
	private static final long serialVersionUID = 2562526738694939398L;
	private Long id;
	private String dep;
	private String ename;
	private Integer ckno;
//	@JSONField(format="yyyy-MM-dd HH:mm:ss")
	private Date clock;
	private Integer mac;
	private Integer no;
	private String way;
	private Integer cdno;

	private String warn;
	
	/**
	 * @return the warn
	 */
	@Transient
	public String getWarn() {
		return warn;
	}

	/**
	 * @param warn the warn to set
	 */
	public void setWarn(String warn) {
		this.warn = warn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "dep", length = 20)
	public String getDep() {
		return this.dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	@Column(name = "ename", length = 10)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "ckno")
	public Integer getCkno() {
		return this.ckno;
	}

	public void setCkno(Integer ckno) {
		this.ckno = ckno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "clock", length = 19)
	public Date getClock() {
		return this.clock;
	}

	public void setClock(Date clock) {
		this.clock = clock;
	}

	@Column(name = "mac")
	public Integer getMac() {
		return this.mac;
	}

	public void setMac(Integer mac) {
		this.mac = mac;
	}

	@Column(name = "no")
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@Column(name = "way", length = 5)
	public String getWay() {
		return this.way;
	}

	public void setWay(String way) {
		this.way = way;
	}

	@Column(name = "cdno")
	public Integer getCdno() {
		return this.cdno;
	}

	public void setCdno(Integer cdno) {
		this.cdno = cdno;
	}

}
